version: '3.8'
services:
  app:
    image: $DOCKER_IMAGE
    build:
       context: .
       dockerfile: Dockerfile
       args:
          KEYCLOAK_ISSUER: $KEYCLOAK_ISSUER
          KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID
          KEYCLOAK_CLIENT_SECRET: $KEYCLOAK_CLIENT_SECRET
          NEXT_PUBLIC_BASE_URL: $NEXT_PUBLIC_BASE_URL
          NEXTAUTH_URL: $NEXTAUTH_URL
          NEXTAUTH_SECRET: $NEXTAUTH_SECRET
          NODE_TLS_REJECT_UNAUTHORIZED: $NODE_TLS_REJECT_UNAUTHORIZED


    environment:
        NEXTAUTH_SECRET: "ij7OXRCIa2KGRjCHUFtDj0SbGRJgnntvz3FM3cVG3FY="
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
    ports:
      - '3000:3000'
